### ISSUE TITLE
ImportError: No module named lib.py3compat 

### ISSUE THREAD

**Issue by mocoap-wang** [shreyansh26/ELF-Miner#2]
thank you for your project,but when I run shell "python  run_system.py" on my own linux system, the project logged error as below:

/root/tmp/elf/file/zfsinfo.mod
Traceback (most recent call last):
  File "ELFMiner.py", line 1, in <module>
    from readelf3 import *
  File "/root/tmp/elf/ELF-Miner-master/readelf3.py", line 23, in <module>
    from elftools.elf.elffile import ELFFile
  File "./elftools/elf/elffile.py", line 23, in <module>
    from ..common.utils import struct_parse, elf_assert
  File "./elftools/common/utils.py", line 12, in <module>
    from ..construct import ConstructError
  File "./elftools/construct/__init__.py", line 33, in <module>
    from .core import *
  File "./elftools/construct/core.py", line 3, in <module>
    from .lib.py3compat import BytesIO, advance_iterator, bchr
ImportError: No module named lib.py3compat

I examine the directories “ ./elftools/construct“, and the lib file is not existing, starved for your answer, thank you

**Comment by DiMaria7** [comment]
求问 您解决这个问题了吗 我也碰到了一样问题555 @evo-cus

**Comment by dyq741** [comment]
Excuse me, have you solved it? I encountered the same issue when running the code.I examine the directories “ ./elftools/construct“, and the lib file is not existing How did you resolve it? Thank you
